# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: hashmapinc/python:dbt

steps:

- task: DownloadSecureProfileFile@1
  name: SettingProfile
  displayName: 'Downloading Profile for Snowflake'
  inputs:
    secureFile: 'snowflake-dbt-demo-profile.yml'

- script: |
    echo Installing $(SettingProfile.secureFilePath) to the ~/.dbt...
    mkdir ~/.dbt
    cp $(SettingProfile.secureFilePath) ~/.dbt
  displayName: Installing Profile for Snowflake
    
- script: |
    cd snowflake_tpc_demo
    dbt compile
    dbt test
    dbt run
  displayName: 'Compile, Test, and Run'
